### ISSUE TITLE
Problem connecting to MQTT-Broker with self-signed certificate

### ISSUE THREAD

**Issue by mikedolx** [fhemberger/mqtt_exporter#63]
Hi.
I'm trying to setup a mqtt-exporter via docker and i'm stuck at connecting to my broker as i'm using a self-signed certificate. I have tried it with the following config.

```yaml
mqtt:
  host: my-broker
  port: 8883
  tls:
    ca_cert: "/conf/certificate.cer"
    certfile: "/conf/certificate.cer"
    keyfile: "/conf/keyfile.key"
  logging:
    level: 'debug'
  auth:
    username: user
    password: password

metrics:
  - name: "observations"
```

When i run the docker container, i get the following error on the docker logs:

```shell
 Starting Prometheus exporter on port: 9344
mqtt       | Traceback (most recent call last):
mqtt       |   File "/usr/src/app/mqtt_exporter.py", line 621, in <module>
mqtt       |     main()
mqtt       |   File "/usr/src/app/mqtt_exporter.py", line 616, in main
mqtt       |     mqtt_client = _mqtt_init(config['mqtt'], config['metrics'])
mqtt       |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mqtt       |   File "/usr/src/app/mqtt_exporter.py", line 358, in _mqtt_init
mqtt       |     mqtt_client.connect(**_strip_config(mqtt_config,
mqtt       |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 941, in connect
mqtt       |     return self.reconnect()
mqtt       |            ^^^^^^^^^^^^^^^^
mqtt       |   File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1104, in reconnect
mqtt       |     sock.do_handshake()
mqtt       |   File "/usr/local/lib/python3.11/ssl.py", line 1346, in do_handshake
mqtt       |     self._sslobj.do_handshake()
mqtt       | ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:992)
```

I have found this docs from python (https://docs.python.org/3/library/ssl.html) but they didn't help me set things up. Is there an option to disable verification of self-signed certificates (i am aware about the implications of if)? 

Thanks!
