### ISSUE TITLE
[Feature Request] enable docker secrets: Using files to provide credentials for basic mqtt authentication

### ISSUE THREAD

**Issue by mikedolx** [fhemberger/mqtt_exporter#64]
Hi,

I have simple feature request: I would like to use files in the mqtt-exporter auth configuration, to be able to use mechanisms like [docker secrets](https://docs.docker.com/compose/use-secrets/).

Here is an example `mqtt-exporter.yml`

```yml
mqtt:
  host: my-broker.com
  port: 1883
  auth:
    username: /path/to/myusernamefile
    password: /path/to/mypassword
```

As i already have the code checked out in my workspace due to another issue 🙄, i'd be able to do the change my self and push a PR to this repo.

Thanks and BR,
Michael
