### ISSUE TITLE
Regex for value replacement is not working

### ISSUE THREAD

**Issue by jce-zz** [fhemberger/mqtt_exporter#67]
I'm trying to extract values from JSON content (coming from a Shelly HT sensor) via value regex with the following config:
```
- name: "shelly_battery_voltage"
    help: "Shelly Battery Voltage"
    type: "gauge"
    topic: "shellies/+/info"
    label_configs:
      - source_labels: ["__value__"]
        regex: ".*voltage.:([0-9.]*)"
        target_label: "__value__"
        replacement: '\1'
        action: 'replace'
```

The JSON content looks like this: 
`{"tmp":{"value":24.00,"units":"C","tC":24.00,"tF":75.20,"is_valid":true},"hum":{"value":70.0,"is_valid":true},"bat":{"value":94,"voltage":2.93},"act_reasons":["sensor"],"connect_retries":0}`

When I try this with a Python RegEx tester it works fine. However, the MQTT_Exporter gives the following error in the log (line 55 is the "regex" line):
yamlreader.yamlreader.YamlReaderError: YAML Error: while scanning a double-quoted scalar
  in "conf/mqtt_exporter.yaml", line 55, column 16
found unknown escape character '.'
  in "conf/mqtt_exporter.yaml", line 55, column 34

How can I specify this regex correctly? Or is there another regex variant to avoid this error?

**Comment by fhemberger** [comment]
Hmm, this is odd. YAML linter doesn't complain about escaping, regex101.com's Python implementation works as well.

Does the same problem occur without the quotes?

```yaml
- name: shelly_battery_voltage
  help: Shelly Battery Voltage
  type: gauge
  topic: shellies/+/info
  label_configs:
    - source_labels: ["__value__"]
      regex: .*voltage.:([0-9.]*)
      target_label: __value__
      replacement: \1
      action: replace
```
